LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := Fennec
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := org.mozilla.fennec_fdroid.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_DEX_PREOPT := false
LOCAL_PRODUCT_MODULE := true

LOCAL_OVERRIDES_PACKAGES := \
    Jelly
include $(BUILD_PREBUILT)
